from sqlalchemy.orm import Session
from app.models.parameter_mapping import ParameterMapping

MAPPINGS = [
    # alias, canonical_name, category, default_unit

    # ── Klinische Chemie – Aliase ─────────────────────────────────────────
    ("Na",                          "Natrium",               "Klinische Chemie", "mmol/l"),
    ("Serum-Na",                    "Natrium",               "Klinische Chemie", "mmol/l"),
    ("K",                           "Kalium",                "Klinische Chemie", "mmol/l"),
    ("Serum-K",                     "Kalium",                "Klinische Chemie", "mmol/l"),
    ("Ca",                          "Calcium",               "Klinische Chemie", "mmol/l"),
    ("Serum-Ca",                    "Calcium",               "Klinische Chemie", "mmol/l"),
    ("Mg",                          "Magnesium",             "Klinische Chemie", "mmol/l"),
    ("Serum-Mg",                    "Magnesium",             "Klinische Chemie", "mmol/l"),
    ("anorg. Phosphat",             "Phosphat",              "Klinische Chemie", "mmol/l"),
    ("Phosphor",                    "Phosphat",              "Klinische Chemie", "mmol/l"),
    ("Cl",                          "Chlorid",               "Klinische Chemie", "mmol/l"),
    ("Glukose",                     "Glucose",               "Klinische Chemie", "mg/dl"),
    ("Blutzucker",                  "Glucose",               "Klinische Chemie", "mg/dl"),
    ("eGFR",                        "GFR (CKD-EPI)",         "Klinische Chemie", "ml/min/1.73m²"),
    ("GFR",                         "GFR (CKD-EPI)",         "Klinische Chemie", "ml/min/1.73m²"),
    ("glomerul. Filtrationsrate",   "GFR (CKD-EPI)",         "Klinische Chemie", "ml/min/1.73m²"),
    ("eGFR CKD-EPI",                "GFR (CKD-EPI)",         "Klinische Chemie", "ml/min/1.73m²"),
    ("Crea",                        "Creatinin",             "Klinische Chemie", "mg/dl"),
    ("Kreatinin",                   "Creatinin",             "Klinische Chemie", "mg/dl"),
    ("BUN",                         "Harnstoff",             "Klinische Chemie", "mg/dl"),
    ("Urea",                        "Harnstoff",             "Klinische Chemie", "mg/dl"),
    ("Urat",                        "Harnsäure",             "Klinische Chemie", "mg/dl"),
    ("Uric acid",                   "Harnsäure",             "Klinische Chemie", "mg/dl"),
    ("Bilirubin gesamt",            "Gesamt-Bilirubin",      "Klinische Chemie", "mg/dl"),
    ("BILG",                        "Gesamt-Bilirubin",      "Klinische Chemie", "mg/dl"),
    ("AST",                         "GOT",                   "Klinische Chemie", "U/l"),
    ("ASAT",                        "GOT",                   "Klinische Chemie", "U/l"),
    ("ALT",                         "GPT",                   "Klinische Chemie", "U/l"),
    ("ALAT",                        "GPT",                   "Klinische Chemie", "U/l"),
    ("Gamma-GT",                    "GGT",                   "Klinische Chemie", "U/l"),
    ("γ-GT",                        "GGT",                   "Klinische Chemie", "U/l"),
    ("Alk. Phosphatase",            "Alkalische Phosphatase","Klinische Chemie", "U/l"),
    ("AP",                          "Alkalische Phosphatase","Klinische Chemie", "U/l"),
    ("ALP",                         "Alkalische Phosphatase","Klinische Chemie", "U/l"),
    ("Lactat Dehydrogenase",        "LDH",                   "Klinische Chemie", "U/l"),
    ("LD",                          "LDH",                   "Klinische Chemie", "U/l"),
    ("CK",                          "CK gesamt",             "Klinische Chemie", "U/l"),
    ("CPK",                         "CK gesamt",             "Klinische Chemie", "U/l"),
    ("Kreatinkinase",               "CK gesamt",             "Klinische Chemie", "U/l"),
    ("Fe",                          "Eisen",                 "Klinische Chemie", "µg/dl"),
    ("Serum-Eisen",                 "Eisen",                 "Klinische Chemie", "µg/dl"),
    ("Eiweiß",                      "Gesamteiweiß",          "Klinische Chemie", "g/dl"),
    ("Total Protein",               "Gesamteiweiß",          "Klinische Chemie", "g/dl"),
    ("TP",                          "Gesamteiweiß",          "Klinische Chemie", "g/dl"),
    ("Gesamt-Eiweiß",               "Gesamteiweiß",          "Klinische Chemie", "g/dl"),
    ("Alb",                         "Albumin",               "Klinische Chemie", "g/dl"),

    # ── Gerinnung – Aliase ────────────────────────────────────────────────
    ("INR",                           "INR",   "Gerinnung", ""),
    ("International Normalized Ratio","INR",   "Gerinnung", ""),
    ("Ratio int. norm.",              "INR",   "Gerinnung", ""),
    ("Quick-Wert",                    "Quick", "Gerinnung", "%"),
    ("Thromboplastinzeit n. Quick",   "Quick", "Gerinnung", "%"),
    ("PTT",                           "PTT",   "Gerinnung", "s"),
    ("Partielle Thromboplastinzeit",  "PTT",   "Gerinnung", "s"),

    # ── Hämatologie – Aliase ──────────────────────────────────────────────
    ("WBC",                        "Leukozyten",              "Hämatologie", "/nl"),
    ("RBC",                        "Erythrozyten",            "Hämatologie", "T/l"),
    ("Hb",                         "Hämoglobin",              "Hämatologie", "g/dl"),
    ("Hkt",                        "Hämatokrit",              "Hämatologie", "%"),
    ("Thrombos",                   "Thrombozyten",            "Hämatologie", "/nl"),
    ("PLT",                        "Thrombozyten",            "Hämatologie", "/nl"),
    ("Mittleres Plättchenvolumen", "MPV",                     "Hämatologie", "fl"),
    ("HbE",                        "MCH",                     "Hämatologie", "pg"),
    ("MCH (HbE)",                  "MCH",                     "Hämatologie", "pg"),
    ("NRBC",                       "% Normoblasten",          "Hämatologie", "%"),
    ("Neutro",                     "Neutrophile",             "Hämatologie", "/nl"),
    ("Lymphos",                    "Lymphozyten",             "Hämatologie", "/nl"),
    ("Monos",                      "Monozyten",               "Hämatologie", "/nl"),
    ("Eos",                        "Eosinophile",             "Hämatologie", "/nl"),
    ("Basos",                      "Basophile",               "Hämatologie", "/nl"),
    ("Neutrophile %",              "% Neutrophile",           "Hämatologie", "%"),
    ("Lymphozyten %",              "% Lymphozyten",           "Hämatologie", "%"),
    ("Monozyten %",                "% Monozyten",             "Hämatologie", "%"),
    ("Eosinophile %",              "% Eosinophile",           "Hämatologie", "%"),
    ("Basophile %",                "% Basophile",             "Hämatologie", "%"),
    ("IG",                         "Unreife Granulozyten",    "Hämatologie", "/nl"),
    ("IG %",                       "% Unreife Granulozyten",  "Hämatologie", "%"),

    # ── Akutbestimmungen – Aliase ─────────────────────────────────────────
    ("CRP",       "C-reaktives Protein", "Akutbestimmungen / TDM / Drogen", "mg/l"),
    ("Lactat",    "Laktat",              "Akutbestimmungen / TDM / Drogen", "mmol/l"),
    ("Troponin I","Troponin",            "Akutbestimmungen / TDM / Drogen", "ng/l"),
    ("Troponin T","Troponin",            "Akutbestimmungen / TDM / Drogen", "ng/l"),
    ("NT-proBNP", "BNP",                "Akutbestimmungen / TDM / Drogen", "pg/ml"),

    # ── Selbst-Mappings (kanonische Namen) ────────────────────────────────
    ("Natrium",               "Natrium",               "Klinische Chemie",              "mmol/l"),
    ("Kalium",                "Kalium",                "Klinische Chemie",              "mmol/l"),
    ("Calcium",               "Calcium",               "Klinische Chemie",              "mmol/l"),
    ("Magnesium",             "Magnesium",             "Klinische Chemie",              "mmol/l"),
    ("Phosphat",              "Phosphat",              "Klinische Chemie",              "mmol/l"),
    ("Chlorid",               "Chlorid",               "Klinische Chemie",              "mmol/l"),
    ("Glucose",               "Glucose",               "Klinische Chemie",              "mg/dl"),
    ("GFR (CKD-EPI)",         "GFR (CKD-EPI)",         "Klinische Chemie",              "ml/min/1.73m²"),
    ("Creatinin",             "Creatinin",             "Klinische Chemie",              "mg/dl"),
    ("Harnstoff",             "Harnstoff",             "Klinische Chemie",              "mg/dl"),
    ("Harnsäure",             "Harnsäure",             "Klinische Chemie",              "mg/dl"),
    ("Gesamt-Bilirubin",      "Gesamt-Bilirubin",      "Klinische Chemie",              "mg/dl"),
    ("GOT",                   "GOT",                   "Klinische Chemie",              "U/l"),
    ("GPT",                   "GPT",                   "Klinische Chemie",              "U/l"),
    ("GLDH",                  "GLDH",                  "Klinische Chemie",              "U/l"),
    ("GGT",                   "GGT",                   "Klinische Chemie",              "U/l"),
    ("Alkalische Phosphatase","Alkalische Phosphatase","Klinische Chemie",              "U/l"),
    ("LDH",                   "LDH",                   "Klinische Chemie",              "U/l"),
    ("CK gesamt",             "CK gesamt",             "Klinische Chemie",              "U/l"),
    ("Amylase",               "Amylase",               "Klinische Chemie",              "U/l"),
    ("Lipase",                "Lipase",                "Klinische Chemie",              "U/l"),
    ("Eisen",                 "Eisen",                 "Klinische Chemie",              "µg/dl"),
    ("Gesamteiweiß",          "Gesamteiweiß",          "Klinische Chemie",              "g/dl"),
    ("Albumin",               "Albumin",               "Klinische Chemie",              "g/dl"),
    ("INR",                   "INR",                   "Gerinnung",                     ""),
    ("Quick",                 "Quick",                 "Gerinnung",                     "%"),
    ("PTT",                   "PTT",                   "Gerinnung",                     "s"),
    ("Leukozyten",            "Leukozyten",            "Hämatologie",                   "/nl"),
    ("Erythrozyten",          "Erythrozyten",          "Hämatologie",                   "T/l"),
    ("Hämoglobin",            "Hämoglobin",            "Hämatologie",                   "g/dl"),
    ("Hämatokrit",            "Hämatokrit",            "Hämatologie",                   "%"),
    ("MCV",                   "MCV",                   "Hämatologie",                   "fl"),
    ("MCH",                   "MCH",                   "Hämatologie",                   "pg"),
    ("MCHC",                  "MCHC",                  "Hämatologie",                   "g/dl"),
    ("Thrombozyten",          "Thrombozyten",          "Hämatologie",                   "/nl"),
    ("MPV",                   "MPV",                   "Hämatologie",                   "fl"),
    ("% Normoblasten",        "% Normoblasten",        "Hämatologie",                   "%"),
    ("Neutrophile",           "Neutrophile",           "Hämatologie",                   "/nl"),
    ("Lymphozyten",           "Lymphozyten",           "Hämatologie",                   "/nl"),
    ("Monozyten",             "Monozyten",             "Hämatologie",                   "/nl"),
    ("Eosinophile",           "Eosinophile",           "Hämatologie",                   "/nl"),
    ("Basophile",             "Basophile",             "Hämatologie",                   "/nl"),
    ("% Neutrophile",         "% Neutrophile",         "Hämatologie",                   "%"),
    ("% Lymphozyten",         "% Lymphozyten",         "Hämatologie",                   "%"),
    ("% Monozyten",           "% Monozyten",           "Hämatologie",                   "%"),
    ("% Eosinophile",         "% Eosinophile",         "Hämatologie",                   "%"),
    ("% Basophile",           "% Basophile",           "Hämatologie",                   "%"),
    ("Unreife Granulozyten",  "Unreife Granulozyten",  "Hämatologie",                   "/nl"),
    ("% Unreife Granulozyten","% Unreife Granulozyten","Hämatologie",                   "%"),
    ("C-reaktives Protein",   "C-reaktives Protein",   "Akutbestimmungen / TDM / Drogen","mg/l"),
    ("Laktat",                "Laktat",                "Akutbestimmungen / TDM / Drogen","mmol/l"),
    ("Troponin",              "Troponin",              "Akutbestimmungen / TDM / Drogen","ng/l"),
    ("BNP",                   "BNP",                   "Akutbestimmungen / TDM / Drogen","pg/ml"),
]


def run_seed(db: Session) -> None:
    for alias, canonical, category, default_unit in MAPPINGS:
        existing = db.query(ParameterMapping).filter_by(alias=alias).first()
        if existing:
            existing.canonical_name = canonical
            existing.category = category
            existing.default_unit = default_unit
        else:
            db.add(ParameterMapping(
                alias=alias,
                canonical_name=canonical,
                category=category,
                default_unit=default_unit,
            ))
    db.commit()
